### ISSUE TITLE
no docs for CDKTF provider AWS Version 10.0.11 in Typescript

### ISSUE THREAD

**Issue by hamza-faethm** [cdklabs/construct-hub#1039]
https://constructs.dev/packages/@cdktf/provider-aws/v/10.0.11/api/FlowLog?lang=typescript does not work
I believe your internal tooling may have broken :( 
Thanks!

What is the URL of the page with the issue?
https://constructs.dev/packages/@cdktf/provider-aws/v/10.0.11/api/FlowLog?lang=typescript

What did you do?
I searched for cdktf provider aws and switched from version 9.x to 10.x

What did you expect to happen?
I expected to see the docs page in a couple of seconds 

What actually happened?
The page doesn't load, it says

Documentation in typescript is still not ready for this package. Come back soon. If this persists, please let us know by creating an issue .

Web Browser
Chrome

OS
MacOS

Other information
Happy to help to fix if you want

**Comment by mrgrain** [comment]
Closing in favor of https://github.com/cdklabs/construct-hub/issues/1114 because it is the same issue.
