### ISSUE TITLE
Missing package @buttonize/cdk in the Construct Hub

### ISSUE THREAD

**Issue by FilipPyrek** [cdklabs/construct-hub#1083]
Hi there,

I've developed a CDK constructs for my project [buttonize.io](https://buttonize.io/) and I want it to be available also in the Construct Hub.

https://www.npmjs.com/package/@buttonize/cdk

I've checked the requirements in https://constructs.dev/contribute 

> Constructs intended for Construct Hub must be published to the [npm Registry ](https://www.npmjs.com/) under Apache, BSD, EPL, MPL-2.0, ISC and CDDL or MIT open source licenses and annotated with a keyword recognized by Construct Hub (awscdk, cdk8s, or cdktf).

- license: MIT ✅ 
- keywords: `aws, aws-cdk, buttonize, cdk, serverless` => ` aws-cdk` ✅ 

> Additionally, since one of the main goals of Construct Hub is to enable an ecosystem of constructs that can be consumed by all CDK languages, your library must be compiled with [JSII ](https://aws.github.io/jsii/), a TypeScript-based tool for building multi-language libraries. Construct Hub leverages the type information produced by the JSII compiler to render a rich multi-language API reference for each construct.

- JSII supports - it's built with `projen` and I can see in the Code explorer in NPM `.jsii` file ✅ 

I've published it couple of days ago but I still don't see it in the Construct Hub.

What did I do wrong?

**Comment by FilipPyrek** [comment]
Any idea what could be wrong @RomainMuller ? 🙂

**Comment by mrgrain** [comment]
The specific package is now deprecated. The new replacement [buttonize](https://www.npmjs.com/package/buttonize) is not a jsii package.
