### ISSUE TITLE
Create `jsii-transpile` tool

### ISSUE THREAD

**Issue by eladb** [cdklabs/construct-hub#11]
**Goal**: given a jsii-enabled package (e.g: the npm `tgz` for the package), install the package & dependencies into a working directory, compile & transliterate all code examples therein into select target languages, then produce a transliterated `.jsii` assembly file as a result.
**How**: `jsii-rosetta` provides the functionality to perform the transliteration, however it does not bother with the dependency management (it is intended to run at build time, not against packaged libraries), and produces a rosetta tablet file instead of a transliterated jsii assembly document.

---

The `jsii-transpile` tool would consume a `.jsii` assembly file, and leverage `jsii-rosetta` APIs to create one `<lang>.jsii` file per configured target language, with all APIs renamed to the correct language representation, and sample code trans-literated to the correct language where possible.

**Comment by RomainMuller** [comment]
Implemented a `jsii-rosetta transliterate` tool instead. This doesn't do exactly the same job (it only does the transliteration, and the dependency resolution, etc... is left to the user, who's more likely to know exactly how to make this happen).
