### ISSUE TITLE
Submodule pages not rendered

### ISSUE THREAD

**Issue by ediv-3nets** [cdklabs/construct-hub#1114]
Page of CDKTF Instance 
URL= https://constructs.dev/packages/@cdktf/provider-aws/v/12.0.4?submodule=instance&lang=typescript
shows empty

**Comment by mrgrain** [comment]
Also applies to later versions and other submodules

**Comment by hamza-faethm** [comment]
It's been like this for a long time now
https://github.com/cdklabs/construct-hub/issues/1039

**Comment by mrgrain** [comment]
Because of this PR https://github.com/cdklabs/construct-hub/pull/1007

**Comment by mrgrain** [comment]
> https://constructs.dev/packages/@cdktf/provider-aws/v/10.0.11/api/FlowLog?lang=typescript does not work I believe your internal tooling may have broken :( Thanks!
> 
> What is the URL of the page with the issue? https://constructs.dev/packages/@cdktf/provider-aws/v/10.0.11/api/FlowLog?lang=typescript
> 
> What did you do? I searched for cdktf provider aws and switched from version 9.x to 10.x
> 
> What did you expect to happen? I expected to see the docs page in a couple of seconds
> 
> What actually happened? The page doesn't load, it says
> 
> Documentation in typescript is still not ready for this package. Come back soon. If this persists, please let us know by creating an issue .
> 
> Web Browser Chrome
> 
> OS MacOS
> 
> Other information Happy to help to fix if you want

**Comment by mrgrain** [comment]
Waiting for deployment and re-processing to confirm.

**Comment by mrgrain** [comment]
Run into an issue with S3 requests being throttled. 

Potential fix: https://github.com/cdklabs/construct-hub/pull/1438

**Comment by mrgrain** [comment]
It ended up being this PR that fixed the throttling: #1442 

But fix is confirmed and will be rolled out to production over the next few days.
