### ISSUE TITLE
new versions are not availble

### ISSUE THREAD

**Issue by kkiani** [cdklabs/construct-hub#1197]
Since version `1.0.5` that we updated the author name and the author's email address, the website does not pull the new versions from npm and the last version that is available is `1.0.5` while the last version is actually `1.1.0` at the time of writing this issue.

- [The package on the NPM](https://www.npmjs.com/package/cost-monitoring-construct)
- [The package on the ConstructHub website](https://constructs.dev/packages/cost-monitoring-construct/v/1.0.5?lang=java)

**Comment by vgkowski** [comment]
+1
same for https://www.npmjs.com/package/aws-analytics-reference-architecture

**Comment by mrgrain** [comment]
We had a backlog. This has been resolved now.
