### ISSUE TITLE
README and documentation not shown for recent versions of @lumigo/cdk-constructs-v2

### ISSUE THREAD

**Issue by mmanciop** [cdklabs/construct-hub#1199]
README and documentation not shown for recent versions of @lumigo/cdk-constructs-v2 ([v0.1.23+](https://constructs.dev/packages/@lumigo/cdk-constructs-v2/v/0.1.23?lang=typescript)). If I should take a guess, I believe it has to do with the [introduction of `@aws-cdk/aws-lambda-python-alpha` as an optional peer dependency](https://github.com/lumigo-io/lumigo-cdk-constructs/commit/02e42f01221caa36e35ba28a16292c6090ee7acc), and specifically the fact that, to keep the `package.json` nicely ordered, the `.projenrc.js` is using `fs` APIs.

**Comment by mmanciop** [comment]
I'll try to use `project.package.addField` instead, but I would have appreciate an error message visible on ConstructHub :-)

**Comment by mmanciop** [comment]
I am not sure it worked: if anything, ConstructHub is erroring out for [v0.1.30](https://constructs.dev/packages/@lumigo/cdk-constructs-v2/v/0.1.30).

**Comment by mrgrain** [comment]
This has been fixed. We didn't expect optional peer deps. Do we do.

**Comment by mmanciop** [comment]
Very cool, thank you @mrgrain !
