### ISSUE TITLE
Officially recognize the Lumigo organization on Construct Hub

### ISSUE THREAD

**Issue by mmanciop** [cdklabs/construct-hub#1200]
Hello there! At [Lumigo](https://lumigo.io/) we love the CDK, and have published the [`@lumigo/cdk-constructs-v2`](https://constructs.dev/packages/@lumigo/cdk-constructs-v2). We would love to have the `Lumigo` publisher recognized as official (we understand it grants an awesome green mark before the publisher name), and have [our logo](https://github.com/lumigo-io/lumigo-kubernetes-operator/tree/main/images) associated with it.

Moreover, on the FAQ it says:

> AWS Partner Network (APN) badge. If you’re an AWS partner and you are publishing a library for your offering, please reach out to us and we will be happy to add a badge to your libraries with your company’s name.

Lumigo is a proud AWS Partner, so we'd love that too :-)

**Comment by mrgrain** [comment]
Hi @mmanciop  I've forwarded your request internally for confirmation.  

> and have [our logo](https://github.com/lumigo-io/lumigo-kubernetes-operator/tree/main/images) associated with it.

Where do you see a logo being used? I believe we currently only put a green checkmark ✅  next to the publisher name.

**Comment by mmanciop** [comment]
@mrgrain I think you are right. I got fooled by the logos on the homepage.

**Comment by mrgrain** [comment]
Hey @mmanciop Do you have a SA or TAM assigned to you? We'd need them to create an internal request to the CDK team, confirming that the request is really coming from you and that all Constructs published in the [lumigo npm namespace](https://www.npmjs.com/org/lumigo) should be considered verified.

**Comment by mmanciop** [comment]
Yes, I'll route to them, thanks :-)

**Comment by mrgrain** [comment]
Excellent! You can have them reach out to me directly if they have questions!

**Comment by mariswa** [comment]
@mrgrain internal ticket: https://t.corp.amazon.com/P93328907

**Comment by mrgrain** [comment]
FYI Code has been merged on our end. Will take a bit to be deployed at the moment.

**Comment by mmanciop** [comment]
@mrgrain if it is deployed, I am not sure it worked
![Screenshot 2023-07-07 at 16 01 45](https://github.com/cdklabs/construct-hub/assets/14020598/9628781a-4f30-49aa-9d29-bd7d31e17ad5)

**Comment by mrgrain** [comment]
Not yet deployed, sorry 🙈 
I'll check back in after the weekend and will let you know when it's there.

**Comment by mrgrain** [comment]
Yeah, I'm missing something here. Will need to look into this further. Stay tuned. 😅

**Comment by mrgrain** [comment]
<img width="307" alt="image" src="https://github.com/cdklabs/construct-hub/assets/379814/3056f8b3-4c30-4d6f-b613-61feefcc7acb">

🥳
