### ISSUE TITLE
Remove Deprecated CDK constructors from Construct Hub

### ISSUE THREAD

**Issue by andreaangiolillo** [cdklabs/construct-hub#1237]
### What is the name of the package that you would like to have removed?

- @mongodbatlas-awscdk/atlas-basic
- @mongodbatlas-awscdk/cluster
- @mongodbatlas-awscdk/project,
- @mongodbatlas-awscdk/database-user
- @mongodbatlas-awscdk/project-ip-access-list
- @mongodbatlas-awscdk/network-container
- @mongodbatlas-awscdk/network-peering
- @mongodbatlas-awscdk/project-invitation
- @mongodbatlas-awscdk/third-party-integration
- @mongodbatlas-awscdk/private-endpoint
- @mongodbatlas-awscdk/encryption-at-rest
- @mongodbatlas-awscdk/cloud-backup-schedule
- @mongodbatlas-awscdk/auditing
- @mongodbatlas-awscdk/search-index
- @mongodbatlas-awscdk/custom-db-role
- @mongodbatlas-awscdk/teams
- @mongodbatlas-awscdk/datalakes
- @mongodbatlas-awscdk/private-endpoint-adl
- @mongodbatlas-awscdk/cloud-backup-snapshot
- @mongodbatlas-awscdk/maintenance-window
- @mongodbatlas-awscdk/org-invitation
- @mongodbatlas-awscdk/ldap-verify
- @mongodbatlas-awscdk/ldap-configuration
- @mongodbatlas-awscdk/online-archive
- @mongodbatlas-awscdk/trigger
- @mongodbatlas-awscdk/alert-configuration
- @mongodbatlas-awscdk/serverless-instance
- @mongodbatlas-awscdk/atlas-integrations
- @mongodbatlas-awscdk/custom-dns-configuration-cluster-aws
- @mongodbatlas-awscdk/cloud-backup-restore-jobs
- @mongodbatlas-awscdk/x509-authentication-database-user
- @mongodbatlas-awscdk/global-cluster-config
- @mongodbatlas-awscdk/private-endpoint-regional-mode
- @mongodbatlas-awscdk/cloud-backup-snapshot-export-bucket
- @mongodbatlas-awscdk/atlas-encryption-at-rest
- @mongodbatlas-awscdk/atlas-basic-private-endpoint
- @mongodbatlas-awscdk/federated-settings-org-role-mapping
- @mongodbatlas-awscdk/mongodb-atlas-project
- awscdk-aa-tst1

### Which versions of the package would you like to remove?

all versions

### Are you the owner of this package?

- [X] I am the owner of this package.

**Comment by andreaangiolillo** [comment]
we're effectively trying to take down all constructs with the **exception** of these two packages as we have since consolidated everything in them: 

1. [awscdk-resources-mongodbatlas](https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.0.2?lang=typescript )
2. [@cdktf/provider-mongodbatlas](https://constructs.dev/packages/@cdktf/provider-mongodbatlas/v/4.0.0?lang=typescript)

Thanks

**Comment by mrgrain** [comment]
Requested packages have been removed.

**Comment by Zuhairahmed** [comment]
thanks @mrgrain, believe we missed one. can you also take down: https://constructs.dev/packages/mongodb-atlas-project/v/1.0.0?lang=typescript ? i'm employee at MongoDB and on same team as @andreaangiolillo

**Comment by andreaangiolillo** [comment]
Hello @mrgrain,
Thanks for the quick response. I noticed a weird behaviour regarding the verification of [awscdk-resources-mongodbatlas](https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.0.2?lang=typescript): when [I search for MongoDB](https://constructs.dev/search?q=MongoDB&offset=0) in ConstructHub, [awscdk-resources-mongodbatlas](https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.0.2?lang=typescript) is shown still with Community instead of MongoDB:

<img width="1432" alt="Screenshot 2023-07-20 at 09 23 22" src="https://github.com/cdklabs/construct-hub/assets/5663078/23e237b7-4477-41e1-b18a-88e7ba533f71">

Once I click on the package, the MongoDB verification is shown correctly 🤔 
<img width="1720" alt="Screenshot 2023-07-20 at 09 27 45" src="https://github.com/cdklabs/construct-hub/assets/5663078/724eab8d-092b-43ea-a124-52e5736e526f">


I am wondering if this is a bug or if we just need to wait a few hours for some updates to take place.

Thanks!

**Comment by mrgrain** [comment]
Well spotted! I think it's a caching issue. Let me have a look.

Could you also confirm @Zuhairahmed 's request please and I'll get it done asap.

**Comment by andreaangiolillo** [comment]
> Could you also confirm @Zuhairahmed 's request please and I'll get it done asap.

yes, I can confirm that we want to remove also that package. Thanks!

**Comment by mrgrain** [comment]
What about this package?
https://constructs.dev/packages/@mongodbatlas-awscdk-test-ma/atlas-integrations-alpha/v/1.0.0-beta.0?lang=typescript

**Comment by andreaangiolillo** [comment]
It should be removed as well 😅 . Thanks!
