### ISSUE TITLE
RSS/Atom feeds haven't been updated in over a month

### ISSUE THREAD

**Issue by mbonig** [cdklabs/construct-hub#1238]
### What is the URL of the page with the issue?

https://constructs.dev/atom

### What did you do?

The last entry in the feed is from June 8th and hasn't been updated since.

### What did you expect to happen?

I expected to see more recent entries

### What actually happened?

I didn't see any entries since June 8th,

### Web Browser

- 

### OS

-

**Comment by truggeriaws** [comment]
@mbonig The feeds are both updated as of today!

```
<lastBuildDate>Thu, 01 Feb 2024 21:03:21 GMT</lastBuildDate>
```

**Comment by mbonig** [comment]
Thank you!
