### ISSUE TITLE
Site is served over http

### ISSUE THREAD

**Issue by poetworrier** [cdklabs/construct-hub#1351]
### What is the URL of the page with the issue?

http://construct.dev

### What did you do?

I visited the page in chrome. 

### What did you expect to happen?

I expected to be sent to an https site

### What actually happened?

I received an insecure page. The browser warned me. `curl` shows `Strict-Transport-Security: max-age=47304000; includeSubDomains`.

### Web Browser

Chrome

### OS

MacOS

**Comment by poetworrier** [comment]
I think this was something on my end. Unsure what although. Feel free to close

**Comment by truggeriaws** [comment]
@poetworrier Thanks for filing this issue. Taking a look in Chrome (v120.0.6099.234), it appears that http requests are being redirected to https.

<img width="504" alt="image" src="https://github.com/cdklabs/construct-hub/assets/139287474/ad603b33-de7d-4d73-b78e-25b63dc40dfa">

We have an [HSTS header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) set as well, as you noted. I don't believe that curl or wget respect HSTS settings and thus are not following the redirect. We will investigate adding an explicit redirect.
