### ISSUE TITLE
ConstructHub is not showing the README file for awscdk-resources-mongodbatlas since v1.2.0

### ISSUE THREAD

**Issue by andreaangiolillo** [cdklabs/construct-hub#1365]
### What is the URL of the page with the issue?

https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/3.0.0?lang=typescript

### What did you do?

I just noticed that ConstructHub is not rendering our README file for [awscdk-resources-mongodbatlas](https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/3.0.0?lang=typescript) since v1.2.0 (ConstructHub shows the README if you select [v1.1.0](https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.1.0?lang=typescript)). We haven't changed the README file after v1.1.0. Could you help us understand what is the problem? Thanks!

### What did you expect to happen?

I would expect the page for v3.0.0 to show the README as the page for [v1.1.0](https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.1.0?lang=typescript)

### Web Browser

Chrome, Firefox

### OS

MacOS

**Comment by pahud** [comment]
Ticket: V1136565930

**Comment by rix0rrr** [comment]
Confirmed the README appears again.
