### ISSUE TITLE
Package not updated on Construct Hub

### ISSUE THREAD

**Issue by krokoko** [cdklabs/construct-hub#1371]
Hi ! We have a constructs package appearing on Construct Hub: https://constructs.dev/packages/@cdklabs/generative-ai-cdk-constructs/v/0.0.82?lang=typescript 

However, it seems newer version of our package are not updated (latest available on Construct Hub is 0.0.82, while latest release is 0.1.13)

**Comment by mrgrain** [comment]
Now available.
