### ISSUE TITLE
Package doesn't appear on constructs.dev

### ISSUE THREAD

**Issue by wladyslawczyzewski** [cdklabs/construct-hub#1416]
Hi,

I just published my first construct lib using projen and it has been successfully published to npmjs.com and pypi.org repos, but for some reason it doesn't appear in constructs.dev index.
I checked if the npm package has `.jsii` file and it does, checked also versions in `.jsii` and `package.json` files – they're the same.

I don't have any idea what else should I change to make that package appear in Construct Hub – docs on the website are very concise. Could you please check the repository and/or npm package and let me know what I have missed? 🙏

Thank you in advance! Links to the lib repo and npm package:

- https://github.com/otocolobus-com/aws-cdk-serverbluegreendeploymentgroup
- https://www.npmjs.com/package/@otocolobus/aws-cdk-serverbluegreendeploymentgroup

**Comment by mrgrain** [comment]
Alright, we have it now: https://constructs.dev/packages/@otocolobus/aws-cdk-serverbluegreendeploymentgroup/v/1.0.1?lang=typescript

**Comment by mrgrain** [comment]
> may I ask what was the reason for this delay? is this something with the construct hub's queue or 3rd party system? I was checking the code in this repo and didn't found the obvious thing why that package didn't appear on the construct.dev website.

Yes of course. ConstructHub uses npmjs.com's [replicate API](https://github.com/npm/registry/blob/main/docs%2FREPLICATE-API.md) to get notified about any changes. This API sometimes (rarely) has a delay.
