### ISSUE TITLE
Implement the Backend X Front-end compatibility model as described in the design RFC.

### ISSUE THREAD

**Issue by iliapolo** [cdklabs/construct-hub#143]
Since documentation is generated on the backend in a background, we need to make sure the webapp knows how to handle multiple versions of documentation pages.

1. Strongly typed interfaces that represent the schema.
2. Enforce major version bumps on breaking changes
3. Front-end heuristic to fetch the correct definition file based on the latest version it support and is available.

More details here: https://github.com/aws/aws-cdk-rfcs/blob/master/text/0324-cdk-construct-hub.md#backend-x-frontend-compatibility

**Comment by addihorowitz** [comment]
This is task is relevant once https://github.com/cdklabs/construct-hub-webapp/issues/171 is implemented
