### ISSUE TITLE
Ingestion: Use CodeArtifact to store packages

### ISSUE THREAD

**Issue by NetaNir** [cdklabs/construct-hub#148]
Currently we store the discovered packages in S3, we suggest that we migrate to use CodeArtifact. There a few reason to do so:

* Easy management of package versions
* Security: We use `npmjs` in the transliteration process. The transliterator Lambda execute `npm install` in order to get to full type definition, required to generate the code snippets in all target language. This means that the function requires full network outbound access in order to reach out to npm. Using CodeArtifact will allow us to block all outbound traffic. 
* Reduce the work required in the ingestion pipeline, we no longer need to download the tarball from npm.js and upload it to s3.

CodeArtifact allows configuring npm as an upstream repo which mean we don't need to mirror npm ourselves (we still need the discovery function to track updates to npm). 

Note that from the ConstructHub operator perspective, this is a drop-in replacement for npmjs, we will implement it as an opt-in feature. 

**open questions**:

* **Cost:** We need to measure the cost difference between CA and S3 per volume of package and traffic.

**Comment by eladb** [comment]
This is done, right @RomainMuller ?

**Comment by RomainMuller** [comment]
This is "done" although we currently still store a copy of the data in S3... We have not quite migrated off that one just yet.
