### ISSUE TITLE
Python docs not available for this package

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub#195]
https://constructs.dev/packages/cdk-tweet-queue/v/1.0.3?lang=python

https://constructs.dev/packages/cdk-dynamo-table-viewer/v/0.1.32?lang=python#usage-typescriptjavascript

https://constructs.dev/packages/cdk-cicd/v/0.1.3?lang=python

Another example:
https://constructs.dev/packages/@aws-cdk/pipelines/v/1.114.0?lang=python

**Comment by iliapolo** [comment]
Resolved by https://github.com/cdklabs/jsii-docgen/pull/373
