### ISSUE TITLE
Images in README are not displayed/resolved

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub#199]
https://constructs.dev/packages/@matthewbonig/nightynight/v/0.1.3?lang=typescript 

Open the GitHub link. You'll see an image in the README file. You can't see it on Construct Hub.

Perhaps it's related to another issue? #198

**Comment by RomainMuller** [comment]
`npmjs.com` apparently handles this by replacing relative URLs/HREFs with a fully-qualified URI obtain day resolving from the GitHub page...

In the case of images... this means `https://raw.githubusercontent.com/<repo-owner>/<repo-name>/HEAD/<relative-path>`. Obviously this only works for GitHub-hosted repositories... and will fail if those are private.
