### ISSUE TITLE
Research: Discovery Function

### ISSUE THREAD

**Issue by RomainMuller** [cdklabs/construct-hub#2]
The `npmjs.com` package registry is backed by a CouchDB database, for which a replica is available for public consumption at `skimdb.npmjs.com`.

The `_changes` endpoint can be used to query the CouchDB for updates from a certain point in time (transaction ID), which would allow a Lambda function to discover new packages without having to resort to a full search on the package registry.

Ideally, the changes should be filtered with application selection criteria (`keywords` should include one of `aws-cdk`, `cdk8s`, `cdktf` or `constructs` -- that list may grow in the future); however no index exists that backs such a search, and it may turn out to be too slow... In which case, filtering client-side may be more effective.

This task is to determine the correct approach to use to ensure a reliable discovery stream. This should also include considerations about error handling (what is and is not retry-able, etc...)

**Comment by MrArnoldPalmer** [comment]
Research resulted in #54 & #55
