### ISSUE TITLE
Storage heavy packages (around 12 packages) are failing because of missing space

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub#230]
Potential solutions: 
* Install without DEV code?
* Deleting large npm files when we don't need them?
* Attach EFS to Lambda ?

* Move to ECS?

**Comment by addihorowitz** [comment]
@RomainMuller can you please update the PR which is in review to the ticket?

**Comment by RomainMuller** [comment]
PR is #261  (now shipped)
