### ISSUE TITLE
General guidance to troubleshoot when construct not appearing in the hub

### ISSUE THREAD

**Issue by kangks** [cdklabs/construct-hub#275]
Any pointers or troubleshooting guides when construct not appearing in the hub?

Construct: https://www.npmjs.com/package/eks-fargate-construct

Thank you!

**Comment by Chriscbr** [comment]
Thanks for reporting - it looks it's available now: https://constructs.dev/packages/eks-fargate-construct/v/1.0.0.

Sometimes the packages take upwards of 10 minutes to get registered, but we'll take a look to see if it's taking longer. There is also an issue currently where some pages are cached longer than intended (including the home page), so you might need to clear your browser cache for it to appear until that is fixed.

**Comment by kangks** [comment]
Hi @Chriscbr I noticed the image is broken - https://constructs.dev/packages/eks-fargate-construct/v/images/EKS-Fargate%20CDK.png is not accessible. 

Do you copy the assets from npmjs? How do I fix it because the image is actually from github in npmjs - https://www.npmjs.com/package/eks-fargate-construct

**Comment by Chriscbr** [comment]
I think assets hosted on GitHub should be visible - I'm not sure why it's not rendering. @gabewomble could you take a look? I'm not too sure on how to debug the react markdown components

**Comment by Chriscbr** [comment]
@kangks Actually it looks like we're already tracking the issue here: https://github.com/cdklabs/construct-hub-webapp/issues/290 - so I'll close this one.
