### ISSUE TITLE
Feature request: RSS feed

### ISSUE THREAD

**Issue by moltar** [cdklabs/construct-hub#279]
Please add RSS feed(s) for:

1. New additions
2. Updated versions

**Comment by allyman17** [comment]
Hey @moltar,

Have you looked at atom? This is how i've set up my RSS feeds https://vilcins.medium.com/rss-feeds-for-your-github-releases-tags-and-activity-cbda2c51373

**Comment by moltar** [comment]
@allyman17 yeah, I use feeds for repo changes too. But I think an official RSS (or Atom) would be better, as it could provide more context, like marking new and updated constructs. Then adding CHANGELOG as the body.

**Comment by mbonig** [comment]
Please re-open!

**Comment by moltar** [comment]
Not stale

https://drewdevault.com/2021/10/26/stalebot.html
