### ISSUE TITLE
Display custom links on package page

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub#286]
![packageinfo](https://user-images.githubusercontent.com/7221111/129608167-9d66d91c-1547-47cc-81e3-ee6d556005a6.png)

The package page currently displays a number of useful links relevant to each package.

![links](https://user-images.githubusercontent.com/7221111/129608254-229c5311-ba4f-4be9-bc2f-3577d25b327c.png)

For user's deploying their own instance of the construct hub, some of these links may not be relevant. For example, an instance of construct hub using a private npm registry may have packages not hosted on public git repositories.

User's deploying their own version of construct hub should be able to specify what content to show in this area of the package page. For example, they could provide an allow-list of values that are defined in a package's `package.json` file. The construct hub frontend would then look for these items in the package information to display them when available.

```ts
new ConstructHub(scope, "ConstructHub", {
  packageLinks: [{ key: 'links.support.email', name: 'Support', value: 'links.support.display' }]
});
```

This would allow package authors to put the following in their package.json

```json
{
  "links": {
    "support": {
      "email": "mailto:someone@mycompany.com",
      "display": "My Company"
    }
  }
}
```

which would be displayed in the package page

![customlinks](https://user-images.githubusercontent.com/7221111/129609727-0d286907-1704-439a-811b-6917ad90c549.png)

This allows the owner of the construct hub instance to arbitrarily control what items are displayed in this section for each package. It can either reference dynamic content that may be unique per package, which requires the author of each package to put that data somewhere it can be read, IE package.json, or something static can be displayed, IE

```ts
new ConstructHub(scope, "ConstructHub", {
  packageLinks: [{ name: 'Support', staticValue: 'www.support.mycompany.com' }]
});
```

**Comment by gabewomble** [comment]
My only nitpick to the proposal is the `_.get` style syntax for keys (`links.support.display`). I think it would be simpler if we use a consistent format for links such as an object with a `display` and `value` property.  The configuration may look something like:

```ts
{
  links: {
    support: {
      display: "Contact the Author",
      ... // Can be expanded to specify an icon type or even predicate functions
    },
    twitter: {
      display: "Twitter",
      icon: "Twitter" // assuming that webapp has a set of icons that can be displayed for this feature
    }
  },
}
```

Now, the only thing package authors would need to do is include the links like so:
```ts
{
  links: {
    support: "mailto:help@acme.com",
    twitter: "https://twitter.com/acme-constructs"
  }
}
```

Let me know your thoughts on this 🙂

**Comment by MrArnoldPalmer** [comment]
@gabewomble yeah I agree I don't like passing a string with `.` to signify potential nesting, but I think its important to be able to access arbitrary keys. For a single link there are more than just key/values, what if you want the link text to be something other than the url? ie `Twitter: <a href="https://twitter.com/me">@me</a>`?

We can also similarly allow passing in functions for formatting similar to tags to limit the complexity of the logic on our end.

**Comment by gabewomble** [comment]
@MrArnoldPalmer 
> We can also similarly allow passing in functions for formatting similar to tags to limit the complexity of the logic on our end.

🔥 I almost suggested this in my write-up earlier as well! We can support properties to set a filtering function or a display function - really just depending on what our consumers need as the proposed model is quite flexible
