### ISSUE TITLE
cdk-prowler not listed

### ISSUE THREAD

**Issue by mmuller88** [cdklabs/construct-hub#296]
I've put the requested keywords. https://github.com/mmuller88/cdk-prowler/blob/main/package.json#L94

```
  "keywords": [
    "audit",
    "aws",
    "awscdk",
    "cdk",
    "hardening",
    "prowler",
    "security"
  ],
```

Search for 'Prowler' in https://constructs.dev/ . It doesn't show up

**Comment by addihorowitz** [comment]
Closing it as the package is available on construct hub.
