### ISSUE TITLE
Implement: Discovery Function

### ISSUE THREAD

**Issue by RomainMuller** [cdklabs/construct-hub#3]
**What**: lambda function, should be executed every 5m
**The goal**: Harvest packages list from npm and notify construct hub 
**Input**: context (last event that was processed = transaction ID)
**Output**: sends notification to SNS topic, payload = link to tmp directory in s3 where the package file is
**How**: the harvesting should start with the last transaction ID, unless we got to the end of the list. Save it to S3. 
**Reference**: Construct Catalog lambda function (take into account this reference retrieves only the latest version of each package). 
**Testing**: process the results and send SNS, Make sure we correctly react to basic network problems 
**Monitoring**: execution of the function (every 5m), #messages of SNS topic, #downloads/execution
 
---

First PR: basic functionality + testing
Second PR: Production ready

---

Implement the discovery function based on the findings documented as a result of #2:

> Create a lambda function or state machine, depending on runtime requirements, that triggers every x (minutes|hours) to poll the `registry.npmjs.org/db/_changes` endpoint and posts any relevant change events to a SNS topic. These change events will include a packages scope, name, id, and any other relevant information for documentation ingestion.
>
> The ingestion functionality should store a `last_event_id` that updates on every run so the following run knows where to begin from. This could be a long running state machine with an optional start parameter that would allow backfilling from any point in time.
>
> The ingestion function should filter on changes related only to packages with the appropriate tags ie: jsii, aws-cdk, etc.

The schema for the SNS notification follows:

```ts
 import { Assembly } from '@jsii/spec';

 export interface IngestionInput {
   /**
    * A unique identifier for the origin that notified about this package
    * version. This may be a UUID generated per-origin. This identifier is used
    * by the front-end application to determine appropriate package installation
    * instructions (e.g: supporting private package registries).
    */
   readonly origin: string;

   /**
    * The contents of the .jsii assembly file that has been disocered and is
    * submitted for injestion in the Construct Hub.
    */
   readonly assembly: Assembly;

   /**
    * The timestamp at which the version has been created in the package
    * registry. When the object is in JSON form, this is encoded as an ISO-8601
    * timestamp, preferrably using the UTC time zone.
    */
   readonly time: Date;

   /**
    * A standardized checksum of the `assembly` and `time` fields formatted in
    * some canonical form. The checksum is encoded as a string with the following
    * format: `<algorithm>-<base64-encoded-hash>`.
    *
    * @example "sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC"
    */
   readonly integrity: string;
 }
 ```

**Comment by NetaNir** [comment]
What about deleted packages?  Example update from the `_changes` endpoint

```js
{
  seq: 14228918,
  id: "eslint-plugin-exclude-strings",
  changes: [
    {
      rev: "2-b8be4b0be0d963b4070c2822d7c31688",
    },
  ],
  deleted: true,
  doc: {
    _id: "eslint-plugin-exclude-strings",
    _rev: "2-b8be4b0be0d963b4070c2822d7c31688",
    _deleted: true,
  },
}
```

We should remove it from our index as well.
