### ISSUE TITLE
Expose CDK Major on Catalog & Metadata

### ISSUE THREAD

**Issue by gabewomble** [cdklabs/construct-hub#326]

**Comment by Chriscbr** [comment]
@gabewomble Is this the same as #326? Perhaps we should close one of these

**Comment by gabewomble** [comment]
@Chriscbr I believe you just linked to this issue 🙂
Is there another one that is a duplicate / is duplicated

**Comment by Chriscbr** [comment]
Whoops! 🤦 I meant this one: #303
