### ISSUE TITLE
Tech Debt: CodeArtifact can be behind npmjs.com

### ISSUE THREAD

**Issue by RomainMuller** [cdklabs/construct-hub#450]
We have identified that CodeArtifact can occasionally fall relatively far behind npmjs.com, which results in inability to generate documentation for packages for a sustained period of time.

This was somewhat mitigated by #446, however this fix cannot be complete, as very recent dependencies of these packages may also be missing from CodeArtifact.

The documentation-generation process either needs to become resilient to this problem, or a more complete solution has to be designed.

**Comment by Chriscbr** [comment]
I think this is no longer an issue since during the documentation generation phase of processing, we are now directly installing from NPM instead of from CodeArtifact.
