### ISSUE TITLE
Some text color matches background

### ISSUE THREAD

**Issue by MarkMcCulloh** [cdklabs/construct-hub#508]
Noticed it on the latest Chrome, but tried other browsers and had the same issue.

![image](https://user-images.githubusercontent.com/1237390/140652381-a9324f31-ff0f-406f-9394-09380b38433e.png)

**Comment by gabewomble** [comment]
Hey! This is related to a bug introduced by an automatic dependency upgrade. Should be fixed by https://github.com/cdklabs/construct-hub-webapp/pull/620
