### ISSUE TITLE
Clear out orchestration DLQ

### ISSUE THREAD

**Issue by iliapolo** [cdklabs/construct-hub#535]
With the current implementation of the transliterator, ingesting packages from `npmjs.com` will result in hundreds of messages in the DLQ due to failures in processing. 

Messages in the DLQ should only be ones we can act on, that is, redrive them through the pipeline after a sporadic error or a code change. 

We need to investigate the DLQ messages at the moment and understand what changes need to be done in order to keep the DLQ clean.

**Comment by iliapolo** [comment]
Some preliminary results.

These are currently the errors we are seeing in the DLQ:

### Corrupt packages 

#### *Type \<X\> not found in assembly*

This error is caused by a corrupted jsii assembly that was created as a result of this bug: https://github.com/aws/jsii/pull/3147

That is, packages compiling with a jsii version <= 1.43.0 would, under specific circumstances, result in corrupted assemblies that we cannot generate docs for. 

The bug has already been fixed, but this will not affect the failures in our pipeline, since the corrupt packages have already been published and cannot be changed.

#### *npm install failed - Fix the upstream dependency conflict, or retry*

This error was observed in a few packages that declared a fixed peerDependency on `constructs`, causing a conflict with one of its other dependencies (for example [cdk8s-mongo-sts](https://github.com/opencdk8s/cdk8s-mongo-sts/blob/v0.0.5/package.json#L60))

------------------------------

**Proposed Solutions**

1. The transliterator should detect such failures and mark those packages as *unprocessable/corrupt*, the state machine should divert such failures away from the DLQ. To keep record of these corrupt packages, we can create a CloudWatch widget that lists them out. 

2. Add the corrupt packages to the deny list. This would however mean that we might need to manually intervene on occasion, when new corrupt packages are published. 

### Timeouts

TBD

**Comment by Chriscbr** [comment]
Really appreciate this investigation Eli! I think both of the proposed solutions sound reasonable to me. I wonder if either of these solutions could be extended to also include behavior for removing packages that have been unpublished, or if it would be better to treat that separately e.g. by detecting those changes within the NpmJs follower - I'm not sure.
