### ISSUE TITLE
Re ingest missing packages

### ISSUE THREAD

**Issue by iliapolo** [cdklabs/construct-hub#536]
For various reasons, it might be the case that messages were lost from the pipeline before properly ingested.

Right now, if a package was discovered and staged, but was lost before it was ingested, we have no way to recover that package apart from doing a complete backfill from npm.

This is because the re-process workflow only operates on packages that were ingested.

We should have a way to detect packages that were discovered, but never ingested, and re-ingest them.

**Comment by Chriscbr** [comment]
How does a package get lost after staging but before it is was ingested? Shouldn't such a package end up in the Staging DLQ?

**Comment by Chriscbr** [comment]
@iliapolo are you still working on this issue?

**Comment by iliapolo** [comment]
Nope. Never really started...unassigning
