### ISSUE TITLE
Missing keywords for some packages

### ISSUE THREAD

**Issue by eladb** [cdklabs/construct-hub#538]
This package is missing keywords: https://constructs.dev/packages/@cdk-cloudformation/awsqs-vpc-vpcqs-module/v/1.1.0-alpha.4?lang=typescript

**Comment by addihorowitz** [comment]
More information about the use case: When the package was first added to Construct Hub it didn't have this keywords. Then it was published again with additional keywords which were not added to Construct Hub

**Comment by gabewomble** [comment]
Actually we just show three keywords, they're not missing in the data. Will update the package header to show them, card behavior will remain the same
