### ISSUE TITLE
Impossible to exit filter modal on mobile

### ISSUE THREAD

**Issue by moltar** [cdklabs/construct-hub#591]
Once the filter modal is opened there's no way to exit it back to the main screen. No buttons are visible.

https://user-images.githubusercontent.com/491247/142771524-a5ab3e02-0c01-47c0-a41c-1f02022a5246.MOV

**Comment by Chriscbr** [comment]
Thanks for the report. This should be fixed by https://github.com/cdklabs/construct-hub-webapp/pull/729, but hasn't been deployed to production yet. I'll double check this works once the change is live.
