### ISSUE TITLE
Category tags should be added on a regular basis as part of the backend processes

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub#625]
Currently we're not adding automated tags for completely new libraries. We should think what's the best way to move the tag generation code to production

**Comment by Chriscbr** [comment]
Briefly discussed this with @gabewomble the other day - one idea that came up was if it's possible to extend our set of `TagCondition`'s to include a tag condition for if the package's README contains certain keywords.

**Comment by Chriscbr** [comment]
Enabled to our prod environment
