### ISSUE TITLE
Region tags on AWS CDK constructs

### ISSUE THREAD

**Issue by dontirun** [cdklabs/construct-hub#638]
Not all services and features are available in all AWS regions. Whether it be community driven or programmatically validated it would be nice to have some insight into whether a construct has been validated to work in a particular region and some sort of grading system for how well it works

**Comment by Chriscbr** [comment]
Great idea! I think if we were to provide this kind of information, it should probably be surfaced programmatically based on the L1/L2 constructs or top-level CDK modules used in the library. This might require adding some kind of metadata to be included in the JSII assembly, or creating some kind of separate tool that determines this information automatically.

This is probably a good candidate for a [RFC](https://github.com/aws/aws-cdk-rfcs)!

**Comment by dontirun** [comment]
It may be beneficial to compare against the available [CloudFormation resource provider schemas](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-type-schemas.html) for a good baseline.  I do think that some human verification may be required for 'non CloudFormation' based factors such as code in Lambda functions that calls out to AWS or external APIs.
