### ISSUE TITLE
Clarification on "best practices for discoverability"

### ISSUE THREAD

**Issue by castodius** [cdklabs/construct-hub#647]
We just published our first package on Construct Hub. While reading the information about contributing we came across the bit about APN.
![image](https://user-images.githubusercontent.com/45800844/145038122-83ac533b-61d2-441d-8568-de7e73991bfb.png)

"reach out to us" is unclear. Does this mean creating an issue here on Github, talking to your AWS TAM or sending an email to some AWS team?

**Comment by castodius** [comment]
Sorry to bother you @addihorowitz , but while I was looking to assist others by having documentation updated I was also hoping for some guidance. We are a partner and would love to have a badge added to our packages. What do we need to do?

**Comment by addihorowitz** [comment]
Hi @castodius, thank you for the question. Can you please reach out through your TAM? We'll be happy to discuss the next steps.
