### ISSUE TITLE
`@cdktf/provider-aws` sometimes fails on timeouts

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/construct-hub#664]
catalog.json is currently missing @cdktf/provider-aws major version 3. (v3.0.0 was published on Dec 2, and v3.0.1 was published on Dec 6).

This should have been automatically added to the catalog, so some investigation into the logs may be required...

**Comment by Chriscbr** [comment]
It looks like the ECS task may be timing out because of how large the package is.

**Comment by Chriscbr** [comment]
Ah I just realized this is the same problem as described by this PR: https://github.com/cdklabs/construct-hub/pull/617. I'll leave this as the tracking issue in the mean time.

**Comment by gabewomble** [comment]
Related to #626

**Comment by iliapolo** [comment]
Reopened. While the root cause of this issue is probably identical to https://github.com/cdklabs/construct-hub/issues/626, i'd still prefer to keep this one as well as a tracking/reminder that we must also validate the existence of this package as well before we consider this issue resolved.

**Comment by iliapolo** [comment]
I stand corrected, this package is actually ingested fine: https://constructs.dev/packages/@cdktf/provider-aws/v/4.0.0?lang=typescript.

We are still seeing occasional timeouts though, so i'm keeping this to track those but reducing priority.
