### ISSUE TITLE
'Newest first' shows 'recently updated' and not 'newest'

### ISSUE THREAD

**Issue by addihorowitz** [cdklabs/construct-hub#676]
I think we should consider separating between 'newest' and 'recently updated'. 
As a user, I expect to find new libraries when I sort by 'newest' and not libraries that were recently updated. 
We can change the wording and/or add a new sort type.

**Comment by gabewomble** [comment]
There are two ways of handling this:

UX Only: Rename the label from `newest` to `recently updated` (simple)

BE: We need to determine if both npm & code artifact expose an original publish date property, that way we can distinguish between recent updates vs package age
