### ISSUE TITLE
My npm package awscdk-nwfirewall is not showing in ConstructHub

### ISSUE THREAD

**Issue by vennemp** [cdklabs/construct-hub#690]
awscdk-nwfirewall

I have added the keywords and the proper license.  I am pretty sure I have added the proper jsii config as I checked other projects where it is working.

Here is that section of package.json

```json
  "jsii": {
    "outdir": "dist",
    "targets": {},
    "tsc": {
      "outDir": "src",
      "rootDir": "lib"
    },
    "excludeTypescript": [
      "example"
    ]
  }
```

**Comment by vennemp** [comment]
This is keywords config 

![image](https://user-images.githubusercontent.com/26049891/147726764-61048205-9531-497a-a778-0c02ad9379ff.png)

**Comment by Chriscbr** [comment]
Hi @vennemp ! The reason your package is not showing in Construct Hub is that there is no `.jsii` file in the generated package. (If you run `npm i awscdk-nwfirewall` in an empty directory and check `node_modules/awscdk-nwfirewall`, the `.jsii` file is nowhere to be found). This file contains important information needed to generate API documentation for your constructs.

Please check the following:
- You are using the `jsii` command to compile your project (this may require adding `jsii` as a dev dependency). When you successfully build your project with jsii, a `.jsii` file will be created in the root of your project. See https://aws.github.io/jsii/user-guides/lib-author/quick-start/set-up/ for more information about setting up jsii.
- If you have a `.npmignore` file, make sure it does not ignore `.jsii` (add "`!.jsii`" to indicate it _should_ be included in the packaged library)
- If you are specifying the `files` field in `package.json`, make sure it includes ".jsii" (this list takes precedence over `.npmignore`)

Let us know if these instructions help!

**Comment by vennemp** [comment]
I appreciate the response!  I am just very new to typescript so this all escapes me.  I will certain check this! 

Coincidentally, I think there is more wrong with my package.  My package works locally on my computer - but when in install fresh from npm it does not.  It won't even recognize the package in my ide - even after installing.  I will get this to work!

**Comment by vennemp** [comment]
Ok I republished using projen as recommended in CDK Book. This should include jsii. But like I said I'm new to this. 

I can now use my package in a fresh app using npm install. 

Been 30 minutes and I put all the tags and still nothing. 

https://www.npmjs.com/package/firewall-construct


Sorry I'm really anxious to publish this for some reason. Is there something else I'm missing?

**Comment by vennemp** [comment]
Ok I got this working!  I appreciate you helping out with this.  Like I said - part of this was my inexperience with TS and all of its dependencies.

I had to publish via the GitHub Actions mechanism generated via projen.  Though I did discover a bug - I had used cdk 2.1 initially so that was what in my .projenrc.js file in cdkVersion.  I kept getting weird version dependency issues on the constructs package.  Switching to 1.97 in the .projenrc.js file immediately fixed that.  What would be the proper forum for reporting this bug?

**Comment by Chriscbr** [comment]
@vennemp I'm glad to hear you were able to get your package published successfully! 😄 

> I kept getting weird version dependency issues on the constructs package.

Is it possible you're trying to use AWS CDK v1 libraries (like `@aws-cdk/core`, `@aws-cdk/aws-ec2`, `@aws-cdk/aws-lambda`) with AWS CDK v2 (available through `aws-cdk-lib`)? If so you might need to change the dependencies you're using and some of the import statements in your code. There's some documentation about differences between v1 and v2 here: https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html

If you run into other issues unrelated to Construct Hub, I would recommend posting a question on the AWS CDK repo or on the <https://cdk.dev/> community slack. Hope this helps! 👍
