### ISSUE TITLE
"cdk8s" featured package card links to old version (v0.33.0)

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/construct-hub#798]
### What is the URL of the page with the issue?

https://constructs.dev/

### What did you do?

Clicked on the cdk8s card listed under "featured packages"

### What did you expect to happen?

I expected to be taken to the latest version of cdk8s.

### What actually happened?

I was taken to cdk8s v0.33.0.

### Other information

Interestingly, this issue does not happen if you just search for cdk8s -- in that user flow, the cdk8s card links to the right version. So it's probably a bug with the featured package logic.

**Comment by ryparker** [comment]
We're updating the featured list so cdk8s will no longer be featured. Will keep this open until we can confirm a similar issue doesn't occur with the updated list.
