### ISSUE TITLE
Initial monitoring

### ISSUE THREAD

**Issue by RomainMuller** [cdklabs/construct-hub#8]
Determine what is needed on a dashboard to facilitate operating of the Construct Hub, including private instances.

Sketch out the organization of a CloudWatch dashboard with all the relevant metrics, alarms, etc... And links to the critical resources that may need quick access.

Monitoring API design from the frontend.
It should be connected to internal alarm system. 
Keep in mind that the app will be public. 

Desired Output: Deploy Canary + metrics + alarms + cloudwatch dashboard + send the metrics to internal alarm system. 
Time estimation: ~2d

**Comment by eladb** [comment]
![Uploading Screen Shot 2021-05-06 at 19.52.48.png…]()

**Comment by eladb** [comment]
Done here.
