### ISSUE TITLE
RSS/Atom feeds are not discoverable

### ISSUE THREAD

**Issue by moltar** [cdklabs/construct-hub#902]
### Description

There is a feed, but no indication of it in the meta data of the page. Thereby the browser will not show the icon to indicate to the visitor that a feed is available.

### Use Case

Discover the feed and sign up.

### Other information

Need to add these to the `<head>`:

```html
<link rel="alternate" type="application/rss+xml" href="https://constructs.dev/rss" />
<link rel="alternate" type="application/atom+xml" href="https://constructs.dev/atom" />
```

**Comment by truggeriaws** [comment]
Hey @moltar, this feature was added shortly before you posted this original issue over in [the webapp repository](https://github.com/cdklabs/construct-hub-webapp). See https://github.com/cdklabs/construct-hub-webapp/pull/962 for details on the implementation over there.

Once the React app loads, it does add the links to https://constructs.dev DOM.

<img width="646" alt="image" src="https://github.com/cdklabs/construct-hub/assets/139287474/2c981b87-0a49-4297-9260-d22b1d391a79">
