### ISSUE TITLE
Why can't I create a Bug issue that's not related to the website?

### ISSUE THREAD

**Issue by Dazza65** [cdklabs/construct-hub#904]
Only 3 issue types exist:

1. Feature Request
2. Remove Package
3. Create bug for ConstructHub website

**Comment by Chriscbr** [comment]
Hi Darren,

Those are the issue types we pre-configured to help address the most common use cases - but if none of those fit, feel free to create a blank issue with your question or bug instead. 🙂

**Comment by Dazza65** [comment]
Issue #905 raised - thanks
