### ISSUE TITLE
cdk-scheduler library does not appear on construct Hub

### ISSUE THREAD

**Issue by Misfits09** [cdklabs/construct-hub#921]
Following the "Contribute" instructions, the [cdk-scheduler](https://www.npmjs.com/package/cdk-scheduler) package has been setup and compiled with JSII (.jsii bundled in package and jsii parameters in `package.json`).
We also added some of the suggested tags for better chances of getting picked up but the library does not appear in Construct Hub (after a week).

Maybe something to do with the fact that our package is [in a subdirectory](https://github.com/guiyom-e/cdk-scheduler/tree/main/cdk-scheduler) of the github repo ?

**Comment by Chriscbr** [comment]
Hi @Misfits09 - can you see if updating the "organization" field in your package.json to a boolean value and re-publishing the library fixes it? See this related issue: https://github.com/cdklabs/construct-hub/issues/900

**Comment by ryparker** [comment]
Hey @Misfits09 can you try Chriscbr's guidance and let us know if you're still not seeing it listed in ConstructHub?

**Comment by mrgrain** [comment]
Close for lack of response. Feel free to open a new issue if the suggested fix doesn't work.
