### ISSUE TITLE
construct hub fails to display non-typescript documentation for libraries with compressed assemblies

### ISSUE THREAD

**Issue by kaizencc** [cdklabs/construct-hub#956]
### What is the URL of the page with the issue?

https://constructs.dev/packages/aws-cdk-lib/v/2.36.0?lang=go

### What did you do?

aws-cdk-lib v2.36.0 does not have language specific documentation. All the documentation is in typescript.

### What did you expect to happen?

I expected examples to be in go for go documentation, java for java documentation, etc.

### What actually happened?

All documentation is in typescript

### Other information

I believe this is due to the jsii-docgen dependency being out of date. Compressed assembly support in jsii-docgen starts at v7.0.56. Construct Hub requires a dependency of 6.3.27 or later. Currently working on verifying this.

**Comment by kaizencc** [comment]
Should be fixed by #959 which adds the necessary jsii-docgen dependency upgrade.

**Comment by MrArnoldPalmer** [comment]
Looks like this is resolved now that #959 is merged.
