### ISSUE TITLE
How can I delete a deprecated construct?

### ISSUE THREAD

**Issue by lordjabez** [cdklabs/construct-hub#970]
I have a construct that I moved to a new namespace, and now need to delete the [old entry](https://constructs.dev/packages/cdk-hyperledger-fabric-network) in construct hub (the corresponding npm package has already been deleted).

How can I remove the package?

**Comment by lordjabez** [comment]
Related issue: https://github.com/cdklabs/construct-hub/issues/343

**Comment by MrArnoldPalmer** [comment]
hey @lordjabez, I'll add this to our deny list for constructs.dev which will remove it. Hopefully we can add support to have these removed automatically as described in #343

**Comment by MrArnoldPalmer** [comment]
@lordjabez this package is now removed, closing for now. For those finding this from good wishing to remove their own deprecated constructs please open your own issue for now and we will remove it.
