### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by iRoachie** [cdklabs/construct-hub#973]
### What is the URL of the page with the issue?

https://constructs.dev/

### What did you do?

Just landed on the homepage.

### What did you expect to happen?

Page should layout correctly

### What actually happened?

Some content is cut off from the page.

The issue starts at around 1280px breakpoint.

<img width="1401" alt="Screen Shot 2022-08-18 at 10 05 20 AM" src="https://user-images.githubusercontent.com/5962998/185415873-a9ec27fa-00e7-497e-b8b3-ff40e6f40abe.png">

### Web Browser

Edge 104.0.1293.54

### OS

Mac

### Other information

Willing to fix this if the src code for the website is available. 
The issue lies really from the set padding on the containers with test-id `homeRedesign-infoSection`.

Better to use a container div that has the padding from the side of the page, then let that container be the grid parent and use CSS gap property instead to give spacing between the columns.

**Comment by MrArnoldPalmer** [comment]
Hey there, here is the source code for the frontend if you wanna take a crack at a fix https://github.com/cdklabs/construct-hub-webapp

**Comment by iRoachie** [comment]
@MrArnoldPalmer opened pr - https://github.com/cdklabs/construct-hub-webapp/pull/1080
