### ISSUE TITLE
Package not published on constructs.dev

### ISSUE THREAD

**Issue by lvthillo** [cdklabs/construct-hub#985]
I'm trying to publish an initial version of [a construct ](https://github.com/lvthillo/cdk-cloudwatch-alarm-chatbot/actions)on constructs.dev. Here is its [npmjs package](https://www.npmjs.com/package/cdk-cloudwatch-alarm-chatbot).
I've read https://constructs.dev/contribute and added the correct tag, license + compiled with jsii.
I'm not sure why it's not available. Can you please help me out?

**Comment by pflorek** [comment]
It will take some time until it's picked up https://constructs.dev/packages/cdk-cloudwatch-alarm-chatbot/v/1.0.3?lang=typescript

**Comment by lvthillo** [comment]
Ow sorry for my impatience!
